import { Product } from '../types/product';

export const mensProducts: Product[] = [
  {
    id: '1',
    name: 'Olive Green Linen Shirt',
    price: 195,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf',
    color: 'Green',
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Topwear',
    description: 'Premium linen shirt perfect for summer days.',
    popularity: 4.5,
    createdAt: new Date('2024-02-15'),
    isLimitedEdition: false
  },
  {
    id: '2',
    name: 'Black Oxford Shirt',
    price: 165,
    image: 'https://images.unsplash.com/photo-1621072156002-e2fccdc0b176',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Topwear',
    description: 'Classic Oxford shirt in premium cotton.',
    popularity: 4.8,
    createdAt: new Date('2024-02-10'),
    isLimitedEdition: false
  },
  {
    id: '3',
    name: 'Textured Black Quarter Zip',
    price: 245,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea',
    color: 'Black',
    sizes: ['M', 'L', 'XL'],
    category: 'Topwear',
    description: 'Luxurious textured quarter zip pullover.',
    popularity: 4.3,
    createdAt: new Date('2024-02-01'),
    isLimitedEdition: false
  },
  {
    id: '4',
    name: 'Dark Green Knitted Polo',
    price: 185,
    image: 'https://images.unsplash.com/photo-1626497764746-6dc36546b388',
    color: 'Green',
    sizes: ['S', 'M', 'L'],
    category: 'Topwear',
    description: 'Sophisticated knitted polo in dark green.',
    popularity: 4.6,
    createdAt: new Date('2024-02-05'),
    isLimitedEdition: false
  },
  {
    id: '5',
    name: 'Navy Blue Silk Shirt',
    price: 295,
    image: 'https://images.unsplash.com/photo-1626497764746-6dc36546b388',
    color: 'Navy',
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Topwear',
    description: 'Limited edition silk shirt with white stripes.',
    popularity: 4.9,
    createdAt: new Date('2024-02-20'),
    isLimitedEdition: true
  },
  {
    id: '6',
    name: 'Cream & Gray Linen Pullups',
    price: 175,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80',
    color: 'Gray',
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Bottomwear',
    description: 'Comfortable linen pullups for casual wear.',
    popularity: 4.4,
    createdAt: new Date('2024-02-12'),
    isLimitedEdition: false
  },
  {
    id: '7',
    name: 'Olive Green Chinos',
    price: 165,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80',
    color: 'Green',
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Bottomwear',
    description: 'Classic chinos in olive green.',
    popularity: 4.7,
    createdAt: new Date('2024-02-08'),
    isLimitedEdition: false
  },
  {
    id: '8',
    name: 'Beige Khaki Pants',
    price: 225,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80',
    color: 'Beige',
    sizes: ['M', 'L', 'XL'],
    category: 'Bottomwear',
    description: 'Limited edition khaki pants in premium cotton.',
    popularity: 4.9,
    createdAt: new Date('2024-02-18'),
    isLimitedEdition: true
  },
  {
    id: '9',
    name: 'Blue Straight Fit Jeans',
    price: 195,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80',
    color: 'Navy',
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Bottomwear',
    description: 'Classic straight fit jeans in dark blue.',
    popularity: 4.5,
    createdAt: new Date('2024-02-03'),
    isLimitedEdition: false
  },
  {
    id: '10',
    name: 'White Linen Shorts',
    price: 145,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80',
    color: 'White',
    sizes: ['S', 'M', 'L'],
    category: 'Bottomwear',
    description: 'Premium linen shorts for summer.',
    popularity: 4.6,
    createdAt: new Date('2024-02-06'),
    isLimitedEdition: false
  }
];